---
application:
  name: "mongo-CRUD-basics"
  project: "mongo-CRUD-basics"
  organization: "QoveryCommunity"
  publicly_accessible: true
  port: 5000
routers:
- name: "main-mongo-CRUD-basics"
  routes:
  - application_name: "mongo-CRUD-basics"
    paths:
    - "/*"
